#!/bin/bash

LIB=/home/collybia

wget https://collybia.com/repo/collybia/arm/rpi4/1.1.0/web_version -O /home/collybia/web_version

MYMPD_VERSION="$(cat /home/collybia/local_version)"
IMAGE_VERSION_WEB="$(cat /home/collybia/web_version)"

echo ${MYMPD_VERSION}
echo ${IMAGE_VERSION_VERSION}
if [[ "$IMAGE_VERSION_WEB" > "$MYMPD_VERSION" ]]; then
    echo "There is an update"
    $LIB/update_os
  else
    echo "No update for the OS"
fi
