#!/bin/bash

LIB=/home/collybia

echo "*** configure: NAS"
var_smb=$(cat /var/lib/mympd/state/nasmode)
if [ "$var_smb" = 1 ]
then
  echo "Configure Samba"
  $LIB/fstab_smb
  elif [ "$var_smb" = 2 ]
  then
    echo "Configure Samba(w/Username/Password)"
    $LIB/fstab_smb
  else [ "$var_smb" = 0 ]
    echo "Samba Disabled"
    $LIB/fstab_smb
fi

echo "*** configure: Mixer Mode"
var_mixer=$(cat /var/lib/mympd/state/volume)
if [ "$var_mixer" = "software" ]
then
  echo "mixer_software"
  $LIB/mixer_software
else
  echo "mixer_disabled"
  $LIB/mixer_none
fi

echo "*** configure: Airplay"
var_airplay=$(cat /var/lib/mympd/state/airplay)
if [ "$var_airplay" = "true" ]
then
  echo "enable_airplay"
  $LIB/enable_airplay
else
  echo "disable_airplay"
  $LIB/disable_airplay
fi

echo "*** configure: UPNP"
var_upnp=$(cat /var/lib/mympd/state/upnp)
if [ "$var_upnp" = "true" ]
then
  echo "enable_upnp"
  $LIB/enable_upnp
else
  echo "disable_upnp"
  $LIB/disable_upnp
fi

echo "*** configure: Spotify"
var_spotify=$(cat /var/lib/mympd/state/spotify)
if [ "$var_spotify" = "true" ]
then
  echo "Enable Spotify"
  $LIB/spotify
else
  echo "Spotify is disabled"
fi

echo "*** configure: Tidal"
var_tidal=$(cat /var/lib/mympd/state/tidal)
if [ "$var_tidal" = "true" ]
then
  echo "Enable Tidal"
  $LIB/tidal
else
  echo "Tidal is disabled"
fi

echo "*** configure: Qobuz"
var_qobuz=$(cat /var/lib/mympd/state/qobuz)
if [ "$var_qobuz" = "true" ]
then
  echo "Enable Qobuz"
  $LIB/qobuz
else
  echo "Qobuz is disabled"
fi