#!/bin/bash

var_nas=$(cat /var/lib/mympd/state/nasmode)

var_nasfolder=$(cat /var/lib/mympd/state/nas_folder)
var_naspath=$(cat /var/lib/mympd/state/nas_path)
var_nasuser=$(cat /var/lib/mympd/state/nas_user)
var_naspass=$(cat /var/lib/mympd/state/nas_pass)

if [ "$var_nas" = 1 ]
then
rm -rf /etc/fstab

cat << _EOF_ > /etc/fstab
# /etc/fstab: static file system information
#
# <file system>	<dir>	<type>	<options>	<dump>	<pass>
/dev/root 	/		ext4	noatime,nouser_xattr,discard     0       0
/dev/mmcblk0p1  /boot vfat    defaults    0       0

#Finetuning for less writes on SD Card - Warning!!! Logs are deleted after each reboot.
tmpfs /var/log tmpfs nodev,nosuid,noatime,mode=1777,size=20m 0 0

#SAMBA Share - Share using username/password
//$var_naspath/$var_nasfolder /mnt/nas-samba cifs vers=2.1,username=guest,password=,ro,uid=mpd,gid=audio,iocharset=utf8,nolock,noauto,x-systemd.automount,x-systemd.device-timeout=10,sec=ntlmssp,rsize=8192,wsize=8192

_EOF_

  elif [ "$var_nas" = 2 ]
  then

  rm -rf /etc/fstab

cat << _EOF_ > /etc/fstab
# /etc/fstab: static file system information
#
# <file system>	<dir>	<type>	<options>	<dump>	<pass>
/dev/root 	/		ext4	noatime,nouser_xattr,discard     0       0
/dev/mmcblk0p1  /boot vfat    defaults    0       0

#Finetuning for less writes on SD Card - Warning!!! Logs are deleted after each reboot.
tmpfs /var/log tmpfs nodev,nosuid,noatime,mode=1777,size=20m 0 0

#SAMBA Share - Share using username/password
//$var_naspath/$var_nasfolder /mnt/nas-samba cifs vers=2.1,username=${var_nasuser},password=${var_naspass},ro,uid=mpd,gid=audio,iocharset=utf8,nolock,noauto,x-systemd.automount,x-systemd.device-timeout=10,sec=ntlmssp,rsize=8192,wsize=8192

_EOF_

  else
  rm -rf /etc/fstab

cat << _EOF_ > /etc/fstab
# /etc/fstab: static file system information
#
# <file system>	<dir>	<type>	<options>	<dump>	<pass>
/dev/root 	/		ext4	noatime,nouser_xattr,discard     0       0
/dev/mmcblk0p1  /boot vfat    defaults    0       0

#Finetuning for less writes on SD Card - Warning!!! Logs are deleted after each reboot.
tmpfs /var/log tmpfs nodev,nosuid,noatime,mode=1777,size=20m 0 0

#SAMBA Share - Public Share
#//xxx.xxx.xxx.xxx/nameofshare /mnt/nas-samba cifs vers=2.1,username=guest,password=,ro,uid=mpd,gid=audio,iocharset=utf8,nolock,noauto,x-systemd.automount,x-systemd.device-timeout=10,sec=ntlmssp,rsize=8048,wsize=8096

#SAMBA Share - Share using username/password
#//xxx.xxx.xxx.xxx/nameofshare /mnt/nas-samba cifs vers=2.1,username=myusername,password=mypassword,ro,uid=mpd,gid=audio,iocharset=utf8,nolock,noauto,x-systemd.automount,x-systemd.device-timeout=10,sec=ntlmssp,rsize=8192,wsize=8192

#NFS Share
#xxx.xxx.xxx.xxx:/nameofshare   /mnt/nas-nfs  nfs4    ro,noauto,x-systemd.automount,x-systemd.device-timeout=10,rsize=8192,wsize=8192

_EOF_

fi
